In [1]:
import pickle
import numpy as np
import scipy

# Hessian

In [4]:
with open('results_data/hbi_output/1234/150_180_extreme/cbm_m1.pkl', 'rb') as f:
    data = pickle.load(f)

In [ ]:
data.math.

In [16]:
P = np.array(data.output.parameters)
H = np.array(data.math.hessian)

In [17]:
print(P.shape)
print(H.shape)    
sum(scipy.linalg.det(H) > 0)          

(150, 2)
(150, 2, 2)


np.int64(150)

In [44]:
Hinv = scipy.linalg.inv(H)
Hinv.shape

(150, 2, 2)

In [49]:
eigvals = np.linalg.eigvalsh(Hinv)
print(eigvals)

[[0.02221759 0.02449972]
 [0.04799684 0.12411634]
 [0.05701562 0.15568177]
 [0.02965069 0.06232275]
 [0.04272096 0.11752047]
 [0.05842214 0.2003652 ]
 [0.04743397 0.14190669]
 [0.02928184 0.06241148]
 [0.03579648 0.06348337]
 [0.07379879 0.37750785]
 [0.12822202 0.17184019]
 [0.02637676 0.0362479 ]
 [0.03560637 0.06752179]
 [0.04415166 0.11599485]
 [0.05941455 0.21418878]
 [0.04711036 0.11704131]
 [0.03861889 0.07572499]
 [0.03880284 0.14607643]
 [0.02218096 0.02446284]
 [0.0226126  0.02543314]
 [0.03820558 0.09329934]
 [0.05934876 0.06862878]
 [0.0824275  0.55230036]
 [0.03658295 0.07706654]
 [0.06190682 0.25625268]
 [0.02482614 0.03028399]
 [0.02738593 0.03630682]
 [0.03318207 0.05592837]
 [0.06054307 0.13642437]
 [0.03972605 0.07881098]
 [0.05847562 0.20334909]
 [0.04102439 0.12852042]
 [0.05847365 0.20333763]
 [0.02218932 0.02447974]
 [0.03122948 0.09782399]
 [0.11151078 0.20876521]
 [0.02259803 0.02532182]
 [0.11694169 0.27725752]
 [0.02693714 0.07163976]
 [0.04228043 0.11465261]


In [46]:
samp = scipy.stats.multivariate_normal.rvs(mean = P[0], cov = Hinv[0], size = 1000, random_state= 1234)

In [48]:
print(P[0])
print(samp[0].mean())
print(samp[1].mean())

[0.08875468 0.01543135]
0.0010635492921339668
0.14181591796828572


In [50]:
import numpy as np
import pandas as pd
import scipy.stats

param_names = ["b0", "bint"] 

n_subjects = H.shape[0]
n_samples  = 1050

dets = np.linalg.det(H)
bad  = np.where(np.abs(dets) < 1e-10)[0]
if len(bad) > 0:
    print(f"Singular Hessian for subjects: {bad + 1}")
else:
    print("All Hessians invertible")

Hinv = np.linalg.inv(H) 



All Hessians invertible


In [53]:
# 2. Sample and build output dict
cols = {}
for i in range(n_subjects):
    samples = scipy.stats.multivariate_normal.rvs(
        mean=P[i], cov=Hinv[i], size=n_samples, random_state=1234 + i
    )  # shape (n_samples, n_params)

    for j, pname in enumerate(param_names):
        cols[f"{pname}[{i + 1}]"] = samples[:, j]

# 3. Save — rows = samples, columns = b0.1, b0.2, ..., bint.1, bint.2, ...
df = pd.DataFrame(cols)
df
#df.to_csv("model1_posteriors.csv", index=False)

,b0[1],bint[1],b0[2],bint[2],b0[3],bint[3],b0[4],bint[4],b0[5],bint[5],...,b0[146],bint[146],b0[147],bint[147],b0[148],bint[148],b0[149],bint[149],b0[150],bint[150]
0,-0.088273,0.090400,-0.170916,2.807094,-2.946762,0.325474,0.919501,1.645467,-0.438391,2.385124,...,-0.653616,1.318752,0.262284,0.971313,-0.420490,1.905252,0.501819,2.470339,0.295040,1.006778
1,0.043643,0.239989,-0.056638,2.808742,-3.032368,0.516758,0.409680,1.331317,-0.534580,2.116526,...,-0.347523,1.055081,-0.114411,1.169531,-0.243812,1.723109,0.524481,2.339555,0.050806,1.059830
2,0.220239,-0.098234,-0.410868,2.303891,-2.440037,0.126298,0.612682,1.443649,-0.824807,2.647218,...,-0.443050,0.967271,0.255765,1.090034,-0.214003,1.898599,0.669052,2.829845,-0.170095,0.731496
3,-0.005227,0.150605,-0.454863,3.060278,-2.645690,-0.086193,0.774197,1.592281,-0.730275,2.273678,...,-0.243737,0.799447,-0.019261,1.348971,-0.476125,1.628849,0.110841,2.318621,0.238605,1.065981
4,-0.245507,0.020109,-0.009889,2.915251,-2.788812,0.718998,0.685769,1.394641,-0.371225,2.815973,...,-0.630958,0.891274,-0.065417,0.960686,-0.188024,1.418544,0.862646,2.223144,0.097837,1.079965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.270659,-0.027268,-0.378506,2.308649,-2.778533,0.690665,0.555740,1.331898,-0.803886,2.247423,...,-0.463197,0.947242,0.058044,0.919896,-0.070992,1.635690,0.398240,1.795270,0.062681,1.144390
996,-0.096408,0.042724,-0.030118,2.506893,-2.616920,0.506706,0.889156,1.640486,-0.959437,2.511690,...,-0.346940,0.949066,0.193201,1.440120,-0.492406,1.452873,0.972379,2.383321,0.135775,1.395861
997,0.183405,0.069365,0.059723,2.589842,-2.663301,0.834192,0.814238,1.806215,-0.535546,2.382206,...,-0.610325,1.216516,0.404652,0.994638,-0.525896,2.033607,0.772499,2.660751,0.030981,1.262495
998,0.207327,0.329793,0.261179,2.449852,-2.324970,0.134512,0.233025,1.251677,-0.897782,2.733344,...,-0.122535,0.996483,-0.252943,0.955258,-0.549378,2.012675,0.398965,2.079030,0.451936,0.861141


In [ ]:
import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from scipy import linalg
from scipy.stats import multivariate_normal

PARAM_NAMES = {
    1: ["b0", "bint"],
    2: ["bext"],
    3: ["b0", "bint", "bext", "z"],
    4: ["b0", "bint", "bext"],
    5: ["guess"],
    6: ["bias1"],
    7: ["bias2"],
}


def check_and_invert(H):
    dets = np.array([linalg.det(H[i]) for i in range(H.shape[0])])
    bad  = np.where(np.abs(dets) < 1e-10)[0]
    if len(bad) > 0:
        print(f" Singular Hessian for subjects: {bad + 1}")
    else:
        print(f" All Hessians invertible")
    return np.array([linalg.inv(H[i]) for i in range(H.shape[0])])


def sample_posterior(P, Hinv, model_number, n_samples=1000, base_seed=1234):
    param_names = PARAM_NAMES[model_number]
    n_subjects  = P.shape[0]
    cols        = {}

    for i in range(n_subjects):
        samples = multivariate_normal.rvs(
            mean=P[i], cov=Hinv[i], size=n_samples, random_state=base_seed + i
        )
        samples = np.atleast_2d(samples)
        if samples.shape[0] != n_samples:
            samples = samples.T

        for j, pname in enumerate(param_names):
            cols[f"{pname}[{i + 1}]"] = samples[:, j]

    return pd.DataFrame(cols)


def generate_all_posteriors(hbi_output_dir="./hbi_output",
                            param_est_dir="./parameter_estimates/hbi",
                            n_samples=1000,
                            base_seed=1234):

    hbi_output_dir = Path(hbi_output_dir)
    param_est_dir  = Path(param_est_dir)

    # Iterate over seeds
    for seed_dir in sorted(hbi_output_dir.iterdir()):
        if not seed_dir.is_dir():
            continue
        seed_name = seed_dir.name
        print(f"\nSeed: {seed_name}")

        # Iterate over datasets within each seed
        for dataset_dir in sorted(seed_dir.iterdir()):
            if not dataset_dir.is_dir():
                continue
            base_name = dataset_dir.name  # e.g. 150_180_equal
            print(f"  Dataset: {base_name}")

            out_dir = param_est_dir / seed_name / "samples"
            out_dir.mkdir(parents=True, exist_ok=True)

            # Iterate over models
            for k, param_names in PARAM_NAMES.items():
                pkl_path = dataset_dir / f"cbm_m{k}.pkl"
                if not pkl_path.exists():
                    print(f"    Missing: {pkl_path}")
                    continue

                with open(pkl_path, "rb") as f:
                    cbm_k = pickle.load(f)

                P = np.array(cbm_k.output.parameters)       # (n_subjects, n_params)
                H = np.array(cbm_k.output.math.hessian)     # (n_subjects, n_params, n_params)

                print(f"    Model {k} ({', '.join(param_names)}): {P.shape[0]} subjects")

                Hinv = check_and_invert(H)
                df   = sample_posterior(P, Hinv, k, n_samples=n_samples, base_seed=base_seed)

                out_path = out_dir / f"{base_name}_posterior_{k}.csv"
                df.to_csv(out_path, index=False)
                print(f" Saved: {out_path}")


if __name__ == "__main__":
    generate_all_posteriors()

# Mean Parameters

In [5]:
with open('./results_data/hbi_output/1234/150_180_equal/150_180_equal_full_output.pkl', 'rb') as f:
    data = pickle.load(f)

In [12]:
[data.parameters[k].shape for k in range(len(data.parameters))]

[(150, 2), (150, 1), (150, 4), (150, 3), (150, 1), (150, 1), (150, 1)]

In [64]:
data.group_mean

[array([[-0.04930637],
        [ 2.42062262]]),
 array([[1.74933829]]),
 array([[-2.18303643],
        [ 2.97877279],
        [ 2.96834314],
        [ 0.84999963]]),
 array([[0.14239942],
        [2.13722486],
        [1.87214948]]),
 array([[0.51285418]]),
 array([[0.04927011]]),
 array([[0.94013018]])]

In [65]:
data.group_hierarchical_errorbar

[array([[0.10081108],
        [0.13956052]]),
 array([[0.10927649]]),
 array([[2.06735181],
        [0.07171798],
        [0.07619217],
        [0.07364213]]),
 array([[0.05725865],
        [0.12667283],
        [0.10767991]]),
 array([[0.00884826]]),
 array([[0.0082226]]),
 array([[0.00824216]])]

In [3]:
with open('results_data/hbi_output/1256/300_360_extreme/300_360_extreme_full_output.pkl', 'rb') as f:
    data = pickle.load(f)

In [4]:
data.group_mean

[array([[0.00328492],
        [2.49614174]]),
 array([[1.8518944]]),
 array([[-0.08364981],
        [ 2.17089775],
        [ 2.02707372],
        [ 0.85009146]]),
 array([[-0.10960839],
        [ 1.86753313],
        [ 1.67095412]]),
 array([[0.49395786]]),
 array([[0.04651549]]),
 array([[0.95032777]])]